name: Build StageDeck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        # Install Qt5 and SDL2 dependencies
        brew install qt@5 sdl2 sdl2_image sdl2_mixer sdl2_ttf portmidi
        
        # Set up Qt5 environment
        echo "LDFLAGS=-L/opt/homebrew/opt/qt@5/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/opt/homebrew/opt/qt@5/include" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/opt/homebrew/opt/qt@5/lib/pkgconfig:/opt/homebrew/lib/pkgconfig" >> $GITHUB_ENV
        echo "/opt/homebrew/opt/qt@5/bin" >> $GITHUB_PATH
        
        # Force link Qt5
        brew link --force qt@5 || true
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip wheel setuptools
        
        # Install platform-specific dependencies
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          # Force binary installations for Windows
          pip install --only-binary :all: pygame==2.6.1 Pillow==11.1.0 numpy==2.2.3
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          # Set up pkg-config for SDL2
          export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig:$PKG_CONFIG_PATH"
          # Install Mac dependencies with binary packages
          pip install --only-binary :all: pygame==2.6.1 PyQt5==5.15.9 PyQt5-Qt5==5.15.2 PyQt5-sip==12.12.2
          # Install remaining packages
          pip install --only-binary :all: Pillow==11.1.0 numpy==2.2.3
        fi
        
        # Install other dependencies
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create icons
      if: matrix.os == 'macos-latest'
      run: |
        # Check if icon.png exists
        if [ -f icon.png ]; then
          # Create iconset directory
          mkdir icon.iconset
          # Generate icons of different sizes
          sips -z 16 16   icon.png --out icon.iconset/icon_16x16.png
          sips -z 32 32   icon.png --out icon.iconset/icon_16x16@2x.png
          sips -z 32 32   icon.png --out icon.iconset/icon_32x32.png
          sips -z 64 64   icon.png --out icon.iconset/icon_32x32@2x.png
          sips -z 128 128 icon.png --out icon.iconset/icon_128x128.png
          sips -z 256 256 icon.png --out icon.iconset/icon_128x128@2x.png
          sips -z 256 256 icon.png --out icon.iconset/icon_256x256.png
          sips -z 512 512 icon.png --out icon.iconset/icon_256x256@2x.png
          sips -z 512 512 icon.png --out icon.iconset/icon_512x512.png
          # Create icns file
          iconutil -c icns icon.iconset
          rm -rf icon.iconset
        fi

    - name: Build with PyInstaller
      shell: bash
      run: |
        pyinstaller stagedeck.spec

    - name: Package Windows Build
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cd dist
        7z a -tzip StageDeck-windows.zip StageDeck/

    - name: Package macOS Build
      if: matrix.os == 'macos-latest'
      run: |
        cd dist
        zip -r StageDeck-macos.zip StageDeck.app/

    - name: Upload Windows Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: StageDeck-windows
        path: dist/StageDeck-windows.zip

    - name: Upload macOS Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: StageDeck-macos
        path: dist/StageDeck-macos.zip
